Store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from orders.views import stripe_webhook_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='index'),
    path('products/', include('products.urls'), name='products'),
    path('users/', include('users.urls'), name='users'),
    path('carts/', include('carts.urls'), name='carts'),
    path('accounts/', include('allauth.urls')),
    path('orders/', include('orders.urls'), name='orders'),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

app/urls.py
from django.urls import path

from .views import home, abouts, chapters, categories, sub_categories


urlpatterns = [
    path('', home, name='index'),
    path('about/<slug:about_slug>/', abouts, name='about'),
    path('chapter/<slug:chapter_slug>/', chapters, name='chapter'),
    path('category/<slug:category_slug>/', categories, name='category'),
    path('category/<slug:category_slug>/<slug:sub_category_slug>/',
         sub_categories, name='sub_categories'),


]

carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart_detail, name="cart_detail"),
    path('add/<str:article>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:id>/',
         views.remove_from_cart, name='remove_from_cart'),
]

products/urls.py
from django.urls import path

from .views import card_of_product


urlpatterns = [
    path('<slug:slug>/', card_of_product, name='cart_of_product'),
]

products/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.text import slugify

import os

from app.models import Category, SubCategory


# * -----WRAPPERS-----
# ? it`s for rename image of product and create folder by articul
def products_filename_wrapper(instance: object, filename: str):
    ext = filename.split('.')[-1]
    filename = '{}.{}'.format(instance.article, ext)

    return os.path.join(f'images/products/{instance.article}/', filename)


class ProductsQuerySet(models.QuerySet):

    def gallery_for_product(self: object, product: object) -> object:
        match(product.category.chapter.name):
            case 'Bicycle':
                galery = models.BicycleGalery.objects.filter(
                    article=product.article)
                return galery
            case 'Accessorie':
                galery = models.BicycleGalery.objects.filter(
                    article=product.article)
                return galery
            case 'Component':
                galery = models.BicycleGalery.objects.filter(
                    article=product.article)
                return galery
            case _:
                return


# * -----PRODUCT`S INCLUDES-----
class Manufacturer(models.Model):
    name = models.CharField(max_length=20, unique=True)
    image = models.FileField(upload_to='images/manufactirers/')
    description = models.TextField(blank=True, null=True)
    slug = models.CharField(max_length=30, editable=False, auto_created=True)

    def save(self: object):
        self.slug = slugify(self.name)
        super().save()

    def __str__(self: object) -> str:
        return f'{self.name}'


class Color(models.Model):
    color = models.CharField(max_length=10)
    rgb = models.CharField(max_length=13)

    def __str__(self: object) -> str:
        return f'{self.color}'


class Size(models.Model):
    short_name = models.CharField(max_length=5)
    minimal = models.IntegerField(validators=[MinValueValidator(0)])
    maximal = models.IntegerField(validators=[MinValueValidator(0)])

    def __str__(self: object) -> str:
        return f'{self.short_name} ({self.minimal} - {self.minimal}cm)'


class WheelSize(models.Model):
    size = models.DecimalField(
        max_digits=10, decimal_places=1, unique=True, validators=[MinValueValidator(6),])

    def __str__(self: object) -> str:
        return f'{self.size}'


class SuspensionTravel(models.Model):
    suspension_travel = models.FloatField(validators=[MinValueValidator(0),],)

    def __str__(self: object) -> str:
        return f'{self.suspension_travel}mm'


class Material(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self: object) -> str:
        return f'{self.name}'


class Weight(models.Model):
    weight = models.FloatField(validators=[MinValueValidator(0),])

    def __str__(self: object) -> str:
        return f'{self.weight}kg'


class Characteristic(models.Model):
    name = models.CharField(max_length=30, unique=True)

    def __str__(self: object) -> str:
        return f'{self.name}'


class CharacteristicValue(models.Model):
    name = models.ForeignKey(Characteristic, on_delete=models.CASCADE)
    description = models.TextField(max_length=50)

    def __str__(self: object) -> str:
        return f'{self.name} - {self.description}'


# * -----PRODUCTS-----
class Product(models.Model):
    manufacturer = models.ForeignKey(
        Manufacturer, blank=True, null=True, on_delete=models.DO_NOTHING)
    label = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    article = models.CharField(max_length=30, unique=True)
    characteristics = models.ManyToManyField(CharacteristicValue, blank=True)
    category = models.ForeignKey(
        Category, on_delete=models.DO_NOTHING, blank=True, null=True)
    subcategory = models.ForeignKey(
        SubCategory, on_delete=models.DO_NOTHING, blank=True, null=True)
    rating = models.FloatField(default=0, validators=[
                               MinValueValidator(0), MaxValueValidator(5)])
    value = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    slug = models.CharField(max_length=50, editable=False, auto_created=True)
    image = models.FileField(upload_to=products_filename_wrapper, blank=True)

    def save(self):
        self.slug = slugify(self.label)
        super().save()

    def __str__(self: object) -> str:
        return f'{self.label}/{self.category}'

    class Meta:
        abstract = True


class Bicycle(Product):
    model = models.CharField(max_length=20)
    color = models.ManyToManyField(Color)
    wheel = models.ForeignKey(WheelSize, on_delete=models.DO_NOTHING)
    frame_size = models.ForeignKey(Size, on_delete=models.DO_NOTHING)
    frame_material = models.ForeignKey(Material, on_delete=models.DO_NOTHING)
    suspension = models.BooleanField(default=False)
    suspension_travel = models.ForeignKey(
        SuspensionTravel, on_delete=models.DO_NOTHING, blank=True, null=True)
    weight = models.ForeignKey(
        Weight, on_delete=models.DO_NOTHING, blank=True, null=True)
    year = models.IntegerField(
        validators=[MinValueValidator(2000)], blank=True, null=True)


class BicycleGalery(models.Model):
    product = models.ForeignKey(
        Bicycle, default=None, on_delete=models.CASCADE)
    article = models.CharField(
        max_length=30, editable=False, auto_created=True)
    image = models.FileField(upload_to=products_filename_wrapper, blank=True)

    def __str__(self: object) -> str:
        return self.product.article

    def save(self: object):
        self.article = self.product.article
        super().save()


class Accessorie(Product):
    color = models.ForeignKey(
        Color, on_delete=models.DO_NOTHING, blank=True, null=True)
    size = models.ForeignKey(
        Size, on_delete=models.DO_NOTHING, blank=True, null=True)
    weight = models.ForeignKey(
        Weight, on_delete=models.DO_NOTHING, blank=True, null=True)
    model = models.CharField(max_length=20, blank=True, null=True)


class AccessorieGalery(models.Model):
    product = models.ForeignKey(
        Accessorie, default=None, on_delete=models.CASCADE)
    article = models.CharField(
        max_length=30, editable=False, auto_created=True)
    image = models.FileField(upload_to=products_filename_wrapper, blank=True)

    def __str__(self: object) -> str:
        return self.product.article

    def save(self: object):
        self.article = self.product.article
        super().save()


class Component(Product):
    color = models.ForeignKey(
        Color, on_delete=models.DO_NOTHING, blank=True, null=True)
    size = models.ForeignKey(
        Size, on_delete=models.DO_NOTHING, blank=True, null=True)
    weight = models.ForeignKey(
        Weight, on_delete=models.DO_NOTHING, blank=True, null=True)
    model = models.CharField(max_length=20, blank=True, null=True)


class ComponentGalery(models.Model):
    product = models.ForeignKey(
        Component, default=None, on_delete=models.CASCADE)
    article = models.CharField(
        max_length=30, editable=False, auto_created=True)
    image = models.FileField(upload_to=products_filename_wrapper, blank=True)

    def __str__(self: object) -> str:
        return self.product.article

    def save(self: object):
        self.article = self.product.article
        super().save()

products/views.py
from django.shortcuts import render
from app import utilites

from .filters import filters


def card_of_product(req: object, slug: str) -> classmethod:
    product = filters(req).get(slug=slug)
    context = {
        'product': product,
        'title': product.label,
        'colors': product.color.all(),
        'characteristics': product.characteristics.all(),
    }

    context.update(utilites.subheader(req))

    return render(req, 'products/products.html', context)

products/templates/products/includes/_card_of_product.html
<div class="card_of_product__wrapper">
    <div class="card_of_product">
        <div class="galery__wrapper">
            <div class="primary_image__wrapper">
                <img src="/media/{{product.image}}" alt="Sorry, no image" class="primary__image">
            </div>

            <div class="galery-list">
                {% for photo in galery %}
                <div class="galery">
                    <img src="/media/{{photo.image}}" alt="Sorry, no image" class="galery-image">
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="product-info">
            <p>
            <h1>{{product.label}}</h1>
            </p>

            <p>manufacturer:
            <h3>{{product.manufacturer}}</h3>
            </p>
            <p>model:
            <h3>{{product.model}}</h3>
            </p>
            <p>rating: {{product.rating}}</p>
            <p>year: {{product.year}}</p>

            <p>article: {{product.article}}</p>

            <p>{{product.description}}</p>

            <p>size:
            <h3>{{product.frame_size}}</h3>
            </p>
            <p>wheel:
            <h3>{{product.wheel}}</h3>
            </p>

            {% for color in colors %}
            <div class="color" style="background-color: rgb{{color.rgb}};">

            </div>
            {% endfor %}
            <p>{{product.color.rgb}}</p>

            <p>price:
            <h3>{{product.price}}</h3>
            </p>

            <div class="product-buttom">
                <a href="{%url 'carts:add_to_cart' product.article %}">
                    <h2>Add to cart</h2>
                </a>
            </div>
        </div>

    </div>

    <h2>characteristics</h2>

    {% for characteristic in characteristics %}
    <div class="characteristics">
        <p>
        <h4>{{characteristic.name}}:</h4>
        </p>
        <p>{{characteristic.description}}</p>
    </div>
    {% endfor %}

</div>

products/templates/products/includes/_paginator.html
{% if products.has_other_pages%}
<nav aria-label="Page pagination example">
    <ul class="paginator">
        {% if products.has_previous %}
        <li class="page-item">
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ products.previous_page_number }}">previous</a>
        </li>
        {% endif %}

        {% for page in products.paginator.page_range %}
        {% if products.number == page %}
        {{page}}

        {% elif page >= products.number|add:-2 and page <= products.number|add:2 %} <li class="page-item">
            <a href="?page={{page}}">
                {{page}}
            </a>
            </li>
            {% endif %}
            {% endfor%}

            {% if products.has_next %}
            <li class="page-item">
                <a href="?page={{ products.next_page_number }}">next</a>
                <a href="?page={{ products.paginator.num_pages }}">last &raquo;</a>
            </li>
            {% endif %}
    </ul>
</nav>
{% endif %}

products/templates/products/includes/_products.html
<div class="product__wrapper">
  <div class="products">
    {% for product in products %}
    <div class="product">
      <div class="product-img" style="background-image: url(/media/{{product.image}})">
        <p class="product_label">
          <a href="/products/{{product.slug}}/">{{product.label }}</a>
        </p>

        {% if product.rating != 0 %}
        <p>
          {{product.rating}}
        </p>
        {% else %}
        <p class="blind-element">
          {{product.rating}}
        </p>
        {% endif %}


        <div class="price">
          {{product.price}}$
        </div>

        <div class="product-menu">
          <div class="product-buttom buy">
            <a href="{%url 'carts:add_to_cart' product.article %}">Add to cart</a>
          </div>

          <div class="product-buttom about">
            <a href="/products/{{product.slug}}/">About</a>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}

  </div>
</div>